export const EMB_ENTRY_FILTER_SECTIONS = [
  {
    key:     "dateRange",
    label:   "Date range",
    type:    "date-range",
    fromKey: "fromDate",
    toKey:   "toDate",
    chipStyle: {
      bg:     "rgba(234,179,8,.1)",
      border: "rgba(234,179,8,.3)",
      color:  "var(--yellow)",
    },
  },
  {
    key:           "status",
    label:         "Status",
    type:          "status",
    statusOptions: ["SUBMITTED", "APPROVED", "REJECTED"],
    chipStyle: {
      bg:     "rgba(34,197,94,.1)",
      border: "rgba(34,197,94,.3)",
      color:  "var(--green)",
    },
  },
  {
    key:          "projects",
    label:        "Project",
    type:         "facet-multi",
    facetKey:     "projectCount",
    entityKey:    "project",
    filterKey:    "projects",
    getId:        (e) => e._id,
    getLabel:     (e) => e.name,
    getSub:       (e) => e.code,
    getChipLabel: (c) => `${c.name} (${c.code})`,
    chipStyle: {
      bg:     "rgba(59,130,246,.1)",
      border: "rgba(59,130,246,.3)",
      color:  "#60A5FA",
    },
  },
  {
    key:          "spans",
    label:        "Span",
    type:         "facet-multi",
    facetKey:     "spanCount",
    entityKey:    "span",
    filterKey:    "spans",
    getId:        (e) => e._id,
    getLabel:     (e) => e.name,
    getSub:       (e) => `${e.startPoint} → ${e.endPoint}`,
    getChipLabel: (c) => c.name,
    chipStyle: {
      bg:     "rgba(255,255,255,.06)",
      border: "var(--border)",
      color:  "var(--text2)",
    },
  },
  {
    key:          "createdBy",
    label:        "Field engineer",
    type:         "facet-multi",
    facetKey:     "createdByCount",
    entityKey:    "createdBy",
    filterKey:    "createdBy",
    role:         "project-admin",
    getId:        (e) => e._id,
    getLabel:     (e) => e.name,
    getSub:       (e) => e.designation,
    getChipLabel: (c) => `${c.name} · ${c.designation}`,
    chipStyle: {
      bg:     "rgba(255,255,255,.06)",
      border: "var(--border)",
      color:  "var(--text2)",
    },
  },
];

export const SPAN_FILTER_SECTIONS = [
  {
    key:           "status",
    label:         "Status",
    type:          "status",
    statusOptions: ["PENDING", "IN_PROGRESS", "COMPLETED"],
    chipStyle: {
      bg:     "rgba(34,197,94,.1)",
      border: "rgba(34,197,94,.3)",
      color:  "var(--green)",
    },
  },
  {
    key:          "projects",
    label:        "Project",
    type:         "facet-multi",
    facetKey:     "projectCount",
    entityKey:    "project",
    filterKey:    "projects",
    getId:        (e) => e._id,
    getLabel:     (e) => e.name,
    getSub:       (e) => e.code,
    getChipLabel: (c) => `${c.name} (${c.code})`,
    chipStyle: {
      bg:     "rgba(59,130,246,.1)",
      border: "rgba(59,130,246,.3)",
      color:  "#60A5FA",
    },
  },
  {
    key:      "startPoint",
    label:    "Start point",
    type:     "facet-string",
    facetKey: "startPointCount",
    valueKey: "startPoint",
    filterKey: "startPoints",
    chipStyle: {
      bg:     "rgba(255,255,255,.06)",
      border: "var(--border)",
      color:  "var(--text2)",
    },
  },
  {
    key:      "endPoint",
    label:    "End point",
    type:     "facet-string",
    facetKey: "endPointCount",
    valueKey: "endPoint",
    filterKey: "endPoints",
    chipStyle: {
      bg:     "rgba(255,255,255,.06)",
      border: "var(--border)",
      color:  "var(--text2)",
    },
  },
];